apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-gateway-sa
  namespace: api-gateway-prod
  labels:
    app: api-gateway
    service: api-gateway
    environment: production
    # EKS specific labels
    app.kubernetes.io/name: api-gateway
    app.kubernetes.io/component: gateway
    app.kubernetes.io/part-of: microservices
    app.kubernetes.io/managed-by: eks
  annotations:
    # EKS IRSA annotation for IAM role association
    eks.amazonaws.com/role-arn: "arn:aws:iam::ACCOUNT-ID:role/api-gateway-eks-role"
    # EKS specific annotations
    eks.amazonaws.com/audience: "sts.amazonaws.com"
    eks.amazonaws.com/sts-regional-endpoints: "true"
---
# IAM Policy document for API Gateway service account
# This should be created as a separate IAM policy and attached to the role
apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-iam-policy
  namespace: api-gateway-prod
  labels:
    app: api-gateway
    type: iam-policy-document
data:
  policy.json: |
    {
      "Version": "2012-10-17",
      "Statement": [
        {
          "Effect": "Allow",
          "Action": [
            "logs:CreateLogGroup",
            "logs:CreateLogStream",
            "logs:PutLogEvents",
            "logs:DescribeLogStreams"
          ],
          "Resource": [
            "arn:aws:logs:*:*:log-group:/aws/eks/api-gateway-prod/*"
          ]
        },
        {
          "Effect": "Allow",
          "Action": [
            "cloudwatch:PutMetricData"
          ],
          "Resource": "*",
          "Condition": {
            "StringEquals": {
              "cloudwatch:namespace": "AWS/ApiGateway"
            }
          }
        }
      ]
    }
