apiVersion: v1
kind: ServiceAccount
metadata:
  name: ms-payment-service-sa
  namespace: ms-payment-service-prod
  labels:
    app: ms-payment-service
    service: ms-payment-service
    environment: production
    # EKS specific labels
    app.kubernetes.io/name: ms-payment-service
    app.kubernetes.io/component: payment-service
    app.kubernetes.io/part-of: microservices
    app.kubernetes.io/managed-by: eks
  annotations:
    # EKS IRSA annotation for IAM role association
    eks.amazonaws.com/role-arn: "arn:aws:iam::ACCOUNT-ID:role/ms-payment-service-eks-role"
    # EKS specific annotations
    eks.amazonaws.com/audience: "sts.amazonaws.com"
    eks.amazonaws.com/sts-regional-endpoints: "true"
---
# IAM Policy document for Payment Service service account
apiVersion: v1
kind: ConfigMap
metadata:
  name: ms-payment-service-iam-policy
  namespace: ms-payment-service-prod
  labels:
    app: ms-payment-service
    type: iam-policy-document
data:
  policy.json: |
    {
      "Version": "2012-10-17",
      "Statement": [
        {
          "Effect": "Allow",
          "Action": [
            "logs:CreateLogGroup",
            "logs:CreateLogStream",
            "logs:PutLogEvents",
            "logs:DescribeLogStreams"
          ],
          "Resource": [
            "arn:aws:logs:*:*:log-group:/aws/eks/ms-payment-service-prod/*"
          ]
        },
        {
          "Effect": "Allow",
          "Action": [
            "secretsmanager:GetSecretValue",
            "secretsmanager:DescribeSecret"
          ],
          "Resource": [
            "arn:aws:secretsmanager:*:*:secret:payment-service/*"
          ]
        },
        {
          "Effect": "Allow",
          "Action": [
            "kms:Decrypt",
            "kms:DescribeKey"
          ],
          "Resource": [
            "arn:aws:kms:*:*:key/*"
          ],
          "Condition": {
            "StringEquals": {
              "kms:ViaService": "secretsmanager.*.amazonaws.com"
            }
          }
        }
      ]
    }
