package com.pacific.customer.domain.model;

import java.time.Instant;

/** Customer Domain Model - Immutable Record Represents the core customer entity in the domain. */
public record Customer(
    String id,
    String email,
    CustomerProfile profile,
    CustomerPreferences preferences,
    CustomerStatus status,
    Instant createdAt,
    Instant updatedAt,
    Long version) {
  public Customer {
    // Validation in compact constructor
    // Allow null ID for new customers (will be generated by MongoDB)
    if (id != null && id.trim().isEmpty()) {
      throw new IllegalArgumentException("Customer ID cannot be empty (but can be null for new customers)");
    }
    if (email == null || email.trim().isEmpty()) {
      throw new IllegalArgumentException("Email cannot be null or empty");
    }
    if (!email.contains("@")) {
      throw new IllegalArgumentException("Invalid email format");
    }
    if (profile == null) {
      throw new IllegalArgumentException("Profile cannot be null");
    }
    if (preferences == null) {
      throw new IllegalArgumentException("Preferences cannot be null");
    }
    if (status == null) {
      throw new IllegalArgumentException("Status cannot be null");
    }
    if (createdAt == null) {
      throw new IllegalArgumentException("Created date cannot be null");
    }
  }

  /** Creates a new customer with ACTIVE status */
  public static Customer createNew(
      String email, CustomerProfile profile, CustomerPreferences preferences) {
    Instant now = Instant.now();
    return new Customer(
        null, // ID will be generated
        email,
        profile,
        preferences,
        CustomerStatus.ACTIVE,
        now,
        now,
        null); // Version should be null for new documents
  }

  /** Creates a customer from existing data with new version */
  public Customer withVersion(Long newVersion) {
    return new Customer(
        id, email, profile, preferences, status, createdAt, Instant.now(), newVersion);
  }

  /** Updates customer profile */
  public Customer withProfile(CustomerProfile newProfile) {
    return new Customer(
        id, email, newProfile, preferences, status, createdAt, Instant.now(), version + 1);
  }

  /** Updates customer preferences */
  public Customer withPreferences(CustomerPreferences newPreferences) {
    return new Customer(
        id, email, profile, newPreferences, status, createdAt, Instant.now(), version + 1);
  }

  /** Changes customer status */
  public Customer withStatus(CustomerStatus newStatus) {
    return new Customer(
        id, email, profile, preferences, newStatus, createdAt, Instant.now(), version + 1);
  }
}
