apiVersion: v1
kind: Namespace
metadata:
  name: auth-service-prod
  labels:
    name: auth-service-prod
    environment: production
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: auth-service-pdb
  namespace: auth-service-prod
  labels:
    app: auth-service
    environment: production
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: auth-service
---
apiVersion: v1
kind: LimitRange
metadata:
  name: auth-service-limits
  namespace: auth-service-prod
spec:
  limits:
  - default:
      cpu: "1000m"
      memory: "2Gi"
    defaultRequest:
      cpu: "250m"
      memory: "512Mi"
    type: Container
  - max:
      cpu: "2000m"
      memory: "4Gi"
    min:
      cpu: "100m"
      memory: "128Mi"
    type: Container
