apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: auth-service-prod
  labels:
    app: auth-service
    service: auth-service
    environment: production
    # EKS specific labels
    app.kubernetes.io/name: auth-service
    app.kubernetes.io/component: authentication
    app.kubernetes.io/part-of: microservices
    app.kubernetes.io/managed-by: eks
  annotations:
    # Service annotations for EKS
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    # Prometheus service discovery
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: auth-service
  sessionAffinity: None
