apiVersion: v1
kind: Service
metadata:
  name: ms-order-service
  namespace: ms-order-service-prod
  labels:
    app: ms-order-service
    service: ms-order-service
    environment: production
    # EKS specific labels
    app.kubernetes.io/name: ms-order-service
    app.kubernetes.io/component: order-service
    app.kubernetes.io/part-of: microservices
    app.kubernetes.io/managed-by: eks
  annotations:
    # Service annotations for EKS
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    # Prometheus service discovery
    prometheus.io/scrape: "true"
    prometheus.io/port: "8081"
spec:
  type: ClusterIP
  ports:
  - port: 8081
    targetPort: 8081
    protocol: TCP
    name: http
  selector:
    app: ms-order-service
  sessionAffinity: None
